#!/usr/bin/env bash
# This displays hours from 0 to 12, minutes from 1 to 59

hrs=0
while [ $hrs -lt 13 ]
do
    echo "Hour: $hrs"
    min=1
    while [ $min -lt 60 ]
    do
        echo $min
	((min+=1))
    done
    ((hrs+=1))
done
